<?php

class __Loader {

	// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	private static $loader_data = [], $plugin_data = [];

	/**
	 * @return string
	 */
	private static function content(){
		$author_name = self::$plugin_data['Author'];
		$author_url = self::$plugin_data['AuthorURI'];
		$autoload = self::$loader_data['autoload'];
		$loader_hook = self::$loader_data['hook_name'];
		$loader_name = self::$loader_data['name'];
		$plugin_basename = self::$loader_data['plugin_basename'];
		$plugin_name = self::$plugin_data['Name'];
		$plugin_url = self::$plugin_data['PluginURI'];
		$content = <<<EOF
<?php
/*
Author: $author_name
Author URI: $author_url
Description: This is automatically generated by the $plugin_name plugin. It is automatically disabled when disabling the main plugin.
License: GPL2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Network: true
Plugin Name: $loader_name
Plugin URI: $plugin_url
Version: 1.0.0
*/

if(defined('ABSPATH') and file_exists(trailingslashit(WP_PLUGIN_DIR) . '$plugin_basename') and file_exists(trailingslashit(WP_PLUGIN_DIR) . '$autoload') and (in_array('$plugin_basename', (array) get_option('active_plugins')) or (function_exists('get_site_option') and array_key_exists('$plugin_basename', (array) get_site_option('active_sitewide_plugins'))))){
	require_once(trailingslashit(WP_PLUGIN_DIR) . '$autoload');
	do_action('$loader_hook');
}

EOF;
		return $content;
	}

	/**
	 * @return void
	 */
	private static function install(){
		$content = self::content();
		$file = trailingslashit(WPMU_PLUGIN_DIR) . self::$loader_data['filename'];
		if(file_exists($file) and md5($content) === md5_file($file)){
			return;
		}
		if(!wp_mkdir_p(WPMU_PLUGIN_DIR)){
			$error = error_get_last();
			$error_msg = __('Could not create directory.');
			if($error){
				$error_msg .= ' ' . __('Error:') . esc_html($error['message']);
			}
			throw new \Exception($error_msg);
		}
		if(!wp_is_writable(WPMU_PLUGIN_DIR)){
			$error = error_get_last();
			$error_msg = __('Destination directory for file streaming does not exist or is not writable.');
			if($error){
				$error_msg .= ' ' . __('Error:') . esc_html($error['message']);
			}
			throw new \Exception($error_msg);
		}
		if(!@file_put_contents($file, $content)){
			$error = error_get_last();
			$error_msg = sprintf(__('&#8220;%s&#8221; has failed to upload.'), wp_basename($file));
			if($error){
				$error_msg .= ' ' . __('Error:') . esc_html($error['message']);
			}
			throw new \Exception($error_msg);
		}
	}

	/**
	 * @return void
	 */
	private static function remove(){
		$file = trailingslashit(WPMU_PLUGIN_DIR) . self::$loader_data['filename'];
		if(!file_exists($file)){
			return;
		}
		if(!@unlink($file)){
			$error = error_get_last();
			$message = __('Error');
			if($error){
				$message = esc_html($error['message']);
			}
			$error_msg = sprintf(__('Plugin could not be deleted due to an error: %s'), $message);
			throw new \Exception($error_msg);
		}
	}

	// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	/**
	 * @return void
	 */
	public static function _activate(){
		$message = '';
		try {
			self::install();
		} catch(\Exception $e){
			$message = $e->getMessage();
		}
		if($message){
			add_action('admin_notices', function(){
				echo '<div class="notice notice-error"><p>' . self::$plugin_data['Name'] . ': ' . $message . '</p></div>';
			});
		}
	}

	/**
	 * @return void
	 */
	public static function _uninstall(){
		$message = '';
		try {
			self::remove();
		} catch(\Exception $e){
			$message = $e->getMessage();
		}
		if($message){
			add_action('admin_notices', function(){
				echo '<div class="notice notice-error"><p>' . self::$plugin_data['Name'] . ': ' . $message . '</p></div>';
			});
		}
	}

	/**
	 * @return void
	 */
	public static function load($file = ''){
		if(!file_exists($file)){
			return;
		}
        if(!function_exists('get_plugin_data')){
			require_once(ABSPATH . 'wp-admin/includes/plugin.php');
		}
        $plugin_data = get_plugin_data($file, false, false);
		$plugin_slug = wp_basename(dirname($file));
		self::$loader_data = [
			'autoload' => $plugin_slug . '/src/php/autoload.php', // Hardcoded.
			'filename' => $plugin_slug . '-loader.php',
			'hook_name' => str_replace('-', '_', $plugin_slug) . '_loaded',
			'name' => $plugin_data['Name'] . ' &#8212; Loader',
            'plugin_basename' => plugin_basename($file),
		];
        self::$plugin_data = $plugin_data;
		register_activation_hook($file, [__CLASS__, '_activate']);
        register_uninstall_hook($file, [__CLASS__, '_uninstall']);
	}

	// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

}
